### ISSUE TITLE
Flickering effect when using popover

### ISSUE THREAD

**Issue by HenryVonfire** [pierrickrouxel/ember-strap#1]
Hi!

I was doing some tests to see if this add-on was suitable for me and I realized that adding to the popover component a `mode="hover"` makes the popover behave in a continuous flickering.

edit: to be more specific, it happens when you move quickly the mouse over the button.

**Comment by pierrickrouxel** [comment]
Hello,
I will try that quickly.
Thanks

**Comment by HenryVonfire** [comment]
Actually, this CSS code seems to solve the problem:

```
.fade {
   opacity: 0;
   -webkit-transition: opacity 0s linear;
      -moz-transition: opacity 0s linear;
       -ms-transition: opacity 0s linear;
        -o-transition: opacity 0s linear;
           transition: opacity 0s linear;
 }
```

**Comment by pierrickrouxel** [comment]
Works for me. Can you try it?

**Comment by HenryVonfire** [comment]
Yes, now works perfectly!
