### ISSUE TITLE
html in tooltip

### ISSUE THREAD

**Issue by shopapps** [pierrickrouxel/ember-strap#5]
Hi,

How can i enable html in the tooltip?  I have tried adding to the component call

    html=true

and also in the sender

    data-html=true

but neither work.

thanks.

**Comment by pierrickrouxel** [comment]
Hi,
tooltips are always in html mode :)

**Comment by shopapps** [comment]
just checking the source and just spotted that..  I wonder why its not working for me then.. :(

I guess it must be something to do with passing values around between components, maybe ember is doing something in the background

**Comment by shopapps** [comment]
rookie mistake!!  i need to wrap my property in 3 braces to allow the html e.g.

    {{#es-tooltip for=tip_id placement='auto left'}}
        {{{tipHtml}}}
      {{/es-tooltip}}
