### ISSUE TITLE
Popover Issues

### ISSUE THREAD

**Issue by ehubbell** [pierrickrouxel/ember-strap#6]
When implementing popovers, I ran into a build error following EmberStrap. When I removed `as |popover|` everything worked fine. I'm also trying to apply a custom animation however I'm running into issues with my transform coming from the top left of the page. Could this be related to Emberstrap? See below for my current implementation.

**EmberStrap Guide**
```
<button class="btn btn-primary" id="popover-example">Show popover</button>
{{#es-popover for="popover-example" as |popover|}}
  Some content
  <button class="btn btn-default" type="button" {{action 'hide' target=popover}}>Close</button>
{{/es-popover}}
```

**Current Implementation**
```
<li>
  {{#link-to 'notifications' id='notifications-popover' role='button'}}
  <i class='icon icon-lightning'></i>
  {{/link-to}}
</li>

{{#es-popover for='notifications-popover' animation=true mode='click' placement='bottom'}} 
Testing this popover! 
{{/es-popover}}
```

**CSS**
```
.popover.bottom.fade {
	position: absolute;
	@include transform(translateX(-10px));
	@include ease(transform);
}
```
Thanks for your help!
Eric

**Comment by pierrickrouxel** [comment]
I think it's not an EmberStrap issue. I never try to override bootstrap animation but if it works without EmberStrap it should be work with it.

**Comment by ehubbell** [comment]
Okay. Will play around a bit more. Thanks

**Comment by pierrickrouxel** [comment]
Is this okay?

**Comment by ehubbell** [comment]
Yep. I tested this out in a test project and came across the same issue. It’s a CSS issue. Thanks for checking. You can close this.

Eric



On Oct 17, 2015, at 5:38 AM, Pierrick Rouxel <notifications@github.com> wrote:

Is this okay?

**Comment by pierrickrouxel** [comment]
Okay thanks for reply.
