### ISSUE TITLE
Title attribute for <a> element is replaced by es-popover

### ISSUE THREAD

**Issue by kashiif** [pierrickrouxel/ember-strap#8]
I have this:

```hbs
 <a href id={{computedId}} {{action 'catchAction'}} title="My Title">Sort</a>

 {{#es-popover class="sortingPopup" placement="auto left" for=computedId as |popover| }}
   ...
   <button  id="{{computedId}}-sort-menu-close" 
                   class="btn btn-default"
                   type="button" 
                   {{action 'hide'    target=popover}}>Close</button>
 {{/es-popover}}
```

This results to render `<a>` as: 

```html
<a href="" id="sort-menu-ember1133" title="" data-ember-action="1134" data-original-title="My Title">Sort</a>
```
and the text in `title` attribute becomes the title of `popover`.

Is there anyway I could actually tell `es-popover` to leave the `title` attribute of the `<a>` element as is and not use it for popover title?

**Comment by pierrickrouxel** [comment]
This is the bootstrap behaviour. Ember-Strap is just a wrapper. 
I can't change this easyly. 
You can extend the popover component to back title at init and restore it after the popover initialization.
